spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    
  mvc:
    static-path-pattern: /static/**
server:
  context-path: /store


#微信公众号配置
#wechat:
# mpAppId: wxd898fcb01713c658
# mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
# openAppId: wx6ad144e54af67d87
# openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
# mchId: 1483469312
# mchKey: 06C56A89949D617xxxxxxxxxxx
# keyPath: /var/weixin_cert/h5.p12
# notifyUrl: http://sell.natapp4.cc/sell/pay/notify
# templateId:
#   orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

#微信url配置
# projectUrl:
#   wechatMpAuthorize: http://sell.natapp4.cc
#   wechatOpenAuthorize: http://sell.natapp4.cc
#   sell: http://sell.natapp4.cc

superAdmin:
  #系统超级管理员名称
  saName: admin
  #系统超级管理员密码(md5加密 123456)
  saPwd: H1AF2G39C90F59F00H5DHA574BA4EE3H
  #超级管理员的ip地址限定,多个用 , 隔开
  saAllowIp:
  #登录地址
  adminPage: /super/admin_index

  #测试输入
  ## commit 病 push




